/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Create_read_write_html;

/**
 *
 * @author mmz
 */
public class Create extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Create() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EditPanel = new javax.swing.JPanel();
        BaslikPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        BaslikTF = new javax.swing.JTextField();
        AciklamaPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        AciklamaTF = new javax.swing.JTextField();
        BaslikButton = new javax.swing.JButton();
        AciklamaDuzenlemePanel = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        UnlemRB = new javax.swing.JRadioButton();
        jPanel20 = new javax.swing.JPanel();
        AciklamaBaslikTF = new javax.swing.JTextField();
        AdresPanel = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        AdresTF = new javax.swing.JTextField();
        XKordinatPanel = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        XKordinatTF = new javax.swing.JTextField();
        YKordinatPanel = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        YKordinatTF = new javax.swing.JTextField();
        ResimPanel = new javax.swing.JPanel();
        ButtonsPanel = new javax.swing.JPanel();
        GosterButton = new javax.swing.JButton();
        KaydetButton = new javax.swing.JButton();
        WebviewPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        EditPanel.setLayout(new java.awt.GridLayout(10, 1));

        BaslikPanel.setLayout(new java.awt.GridLayout());

        jPanel4.setLayout(new java.awt.GridLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BAŞLIK");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel1);

        BaslikPanel.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout());

        BaslikTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaslikTFActionPerformed(evt);
            }
        });
        jPanel5.add(BaslikTF);

        BaslikPanel.add(jPanel5);

        EditPanel.add(BaslikPanel);

        AciklamaPanel.setLayout(new java.awt.GridLayout());

        jPanel7.setLayout(new java.awt.GridLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AÇIKLAMA");
        jPanel7.add(jLabel2);

        AciklamaPanel.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout());

        AciklamaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AciklamaTFActionPerformed(evt);
            }
        });
        jPanel8.add(AciklamaTF);

        BaslikButton.setText("AÇIKLAMAYA BAŞLIK EKLE");
        jPanel8.add(BaslikButton);

        AciklamaPanel.add(jPanel8);

        EditPanel.add(AciklamaPanel);

        AciklamaDuzenlemePanel.setLayout(new java.awt.GridLayout());

        jPanel19.setLayout(new java.awt.GridLayout());

        UnlemRB.setText("Ünlem");
        UnlemRB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        UnlemRB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UnlemRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnlemRBActionPerformed(evt);
            }
        });
        jPanel19.add(UnlemRB);

        AciklamaDuzenlemePanel.add(jPanel19);

        jPanel20.setLayout(new java.awt.GridLayout());

        AciklamaBaslikTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AciklamaBaslikTFActionPerformed(evt);
            }
        });
        jPanel20.add(AciklamaBaslikTF);

        AciklamaDuzenlemePanel.add(jPanel20);

        EditPanel.add(AciklamaDuzenlemePanel);

        AdresPanel.setLayout(new java.awt.GridLayout());

        jPanel10.setLayout(new java.awt.GridLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADRES");
        jPanel10.add(jLabel3);

        AdresPanel.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridLayout());

        AdresTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdresTFActionPerformed(evt);
            }
        });
        jPanel11.add(AdresTF);

        AdresPanel.add(jPanel11);

        EditPanel.add(AdresPanel);

        XKordinatPanel.setLayout(new java.awt.GridLayout());

        jPanel13.setLayout(new java.awt.GridLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("KORDİNATLAR X");
        jPanel13.add(jLabel4);

        XKordinatPanel.add(jPanel13);

        jPanel14.setLayout(new java.awt.GridLayout());

        XKordinatTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XKordinatTFActionPerformed(evt);
            }
        });
        jPanel14.add(XKordinatTF);

        XKordinatPanel.add(jPanel14);

        EditPanel.add(XKordinatPanel);

        YKordinatPanel.setLayout(new java.awt.GridLayout());

        jPanel16.setLayout(new java.awt.GridLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("KORDİNATLAR Y");
        jPanel16.add(jLabel5);

        YKordinatPanel.add(jPanel16);

        jPanel17.setLayout(new java.awt.GridLayout());

        YKordinatTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YKordinatTFActionPerformed(evt);
            }
        });
        jPanel17.add(YKordinatTF);

        YKordinatPanel.add(jPanel17);

        EditPanel.add(YKordinatPanel);

        javax.swing.GroupLayout ResimPanelLayout = new javax.swing.GroupLayout(ResimPanel);
        ResimPanel.setLayout(ResimPanelLayout);
        ResimPanelLayout.setHorizontalGroup(
            ResimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        ResimPanelLayout.setVerticalGroup(
            ResimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        EditPanel.add(ResimPanel);

        ButtonsPanel.setLayout(new java.awt.GridLayout(1, 2));

        GosterButton.setText("GÖSTER");
        GosterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GosterButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(GosterButton);

        KaydetButton.setText("KAYDET");
        ButtonsPanel.add(KaydetButton);

        EditPanel.add(ButtonsPanel);

        jScrollPane1.setViewportView(EditPanel);

        jPanel1.add(jScrollPane1);

        javax.swing.GroupLayout WebviewPanelLayout = new javax.swing.GroupLayout(WebviewPanel);
        WebviewPanel.setLayout(WebviewPanelLayout);
        WebviewPanelLayout.setHorizontalGroup(
            WebviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        WebviewPanelLayout.setVerticalGroup(
            WebviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );

        jPanel1.add(WebviewPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1247, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BaslikTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaslikTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BaslikTFActionPerformed

    private void AciklamaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AciklamaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AciklamaTFActionPerformed

    private void AdresTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdresTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdresTFActionPerformed

    private void XKordinatTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XKordinatTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XKordinatTFActionPerformed

    private void YKordinatTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YKordinatTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YKordinatTFActionPerformed

    private void AciklamaBaslikTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AciklamaBaslikTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AciklamaBaslikTFActionPerformed

    private void UnlemRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnlemRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnlemRBActionPerformed

    private void GosterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GosterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GosterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AciklamaBaslikTF;
    private javax.swing.JPanel AciklamaDuzenlemePanel;
    private javax.swing.JPanel AciklamaPanel;
    private javax.swing.JTextField AciklamaTF;
    private javax.swing.JPanel AdresPanel;
    private javax.swing.JTextField AdresTF;
    private javax.swing.JButton BaslikButton;
    private javax.swing.JPanel BaslikPanel;
    private javax.swing.JTextField BaslikTF;
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JPanel EditPanel;
    private javax.swing.JButton GosterButton;
    private javax.swing.JButton KaydetButton;
    private javax.swing.JPanel ResimPanel;
    private javax.swing.JRadioButton UnlemRB;
    private javax.swing.JPanel WebviewPanel;
    private javax.swing.JPanel XKordinatPanel;
    private javax.swing.JTextField XKordinatTF;
    private javax.swing.JPanel YKordinatPanel;
    private javax.swing.JTextField YKordinatTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
